# 组件
units:
  - name: A  # 组件名
    install: A_installDemo  #安装方法
    next: [D,E]  # 依赖A的其他组件
  - name: B
    install: B_installDemo
    next: [E]
  - name: C
    install: C_installDemo
    next: [F]
  - name: D
    install: D_installDemo
    next: [G]
  - name: E
    install: E_installDemo
    next: [G]
  - name: F
    install: F_installDemo
    next: [H]
  - name: G
    install: G_installDemo
    next: [H]
  - name: H
    install: H_installDemo
    next: